name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.5.0"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.5"

      - name: Create local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: zenin-messenger-debug
          path: build/app/outputs/flutter-apk/app-debug.apk